[opener]
edit = [
    { run = "nvim %*", block = true, desc = "Neovim" },
    { run = "neovide %*", desc = "Neovide" },
    { run = 'notepad "%*"', desc = "Notepad" },
    { run = 'start %*', desc = "Default" },
]
